# Form implementation generated from reading ui file '.\layout.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(882, 516)
        self.nameEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.nameEdit.setGeometry(QtCore.QRect(100, 70, 113, 20))
        self.nameEdit.setObjectName("nameEdit")
        self.umowa_o_praceCheckbox = QtWidgets.QCheckBox(parent=Dialog)
        self.umowa_o_praceCheckbox.setGeometry(QtCore.QRect(60, 200, 101, 17))
        self.umowa_o_praceCheckbox.setObjectName("umowa_o_praceCheckbox")
        self.nameLabel = QtWidgets.QLabel(parent=Dialog)
        self.nameLabel.setGeometry(QtCore.QRect(30, 80, 47, 13))
        self.nameLabel.setObjectName("nameLabel")
        self.surnameLabel = QtWidgets.QLabel(parent=Dialog)
        self.surnameLabel.setGeometry(QtCore.QRect(20, 110, 47, 13))
        self.surnameLabel.setObjectName("surnameLabel")
        self.surname = QtWidgets.QLineEdit(parent=Dialog)
        self.surname.setGeometry(QtCore.QRect(100, 100, 113, 20))
        self.surname.setObjectName("surname")
        self.peselLabel = QtWidgets.QLabel(parent=Dialog)
        self.peselLabel.setGeometry(QtCore.QRect(30, 140, 47, 13))
        self.peselLabel.setObjectName("peselLabel")
        self.id = QtWidgets.QLineEdit(parent=Dialog)
        self.id.setGeometry(QtCore.QRect(100, 130, 113, 20))
        self.id.setObjectName("id")
        self.submit = QtWidgets.QPushButton(parent=Dialog)
        self.submit.setGeometry(QtCore.QRect(110, 260, 75, 23))
        self.submit.setObjectName("submit")
        self.result = QtWidgets.QLabel(parent=Dialog)
        self.result.setGeometry(QtCore.QRect(0, 340, 881, 61))
        self.result.setText("")
        self.result.setObjectName("result")
        self.phoneNumber = QtWidgets.QLineEdit(parent=Dialog)
        self.phoneNumber.setGeometry(QtCore.QRect(100, 160, 113, 20))
        self.phoneNumber.setObjectName("phoneNumber")
        self.peselLabel_2 = QtWidgets.QLabel(parent=Dialog)
        self.peselLabel_2.setGeometry(QtCore.QRect(20, 160, 71, 16))
        self.peselLabel_2.setObjectName("peselLabel_2")
        self.employeesList = QtWidgets.QListWidget(parent=Dialog)
        self.employeesList.setGeometry(QtCore.QRect(500, 50, 256, 192))
        self.employeesList.setObjectName("employeesList")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Pracownicy"))
        self.umowa_o_praceCheckbox.setText(_translate("Dialog", "Umowa o pracę"))
        self.nameLabel.setText(_translate("Dialog", "Imię"))
        self.surnameLabel.setText(_translate("Dialog", "Nazwisko"))
        self.peselLabel.setText(_translate("Dialog", "PESEL"))
        self.submit.setText(_translate("Dialog", "Zapisz"))
        self.peselLabel_2.setText(_translate("Dialog", "nr telefonu"))
